2025-02-21 18:29:03,426 : INFO : root : Loading config.
2025-02-21 18:29:03,427 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-02-21 18:29:03,428 : WARNING : ConfigProcessor : Config file in cache changed: /Users/andre/Napoleon/config/config.yaml
2025-02-21 18:29:03,428 : INFO : ConfigProcessor : Loading config from file /Users/andre/mpf/lib/python3.11/site-packages/mpf/mpfconfig.yaml.
2025-02-21 18:29:03,432 : INFO : ConfigProcessor : Loading config: /Users/andre/mpf/lib/python3.11/site-packages/mpf/mpfconfig.yaml
2025-02-21 18:29:03,432 : INFO : ConfigProcessor : Loading config from file /Users/andre/Napoleon/config/config.yaml.
2025-02-21 18:29:03,433 : INFO : ConfigProcessor : Loading config: /Users/andre/Napoleon/config/config.yaml
2025-02-21 18:29:03,433 : INFO : ConfigProcessor : Loading config: /Users/andre/Napoleon/config/config_ball_devices.yaml
2025-02-21 18:29:03,434 : INFO : ConfigProcessor : Loading config: /Users/andre/Napoleon/config/config_coils.yaml
2025-02-21 18:29:03,435 : INFO : ConfigProcessor : Loading config: /Users/andre/Napoleon/config/config_switches.yaml
2025-02-21 18:29:03,435 : INFO : ConfigProcessor : Config file cache created: /var/folders/np/pd6clpgx1xs_0sdwz71m1gyh0000gn/T/0e92bbbc1117f2a7fed5bfc9fd49c3ff.mpf_cache
2025-02-21 18:29:03,452 : INFO : ConfigProcessor : Loading config from cache: /var/folders/np/pd6clpgx1xs_0sdwz71m1gyh0000gn/T/1a4610a235e3724f4c88b7b6a3726c72.mpf_cache
2025-02-21 18:29:03,453 : INFO : ConfigProcessor : Loading config from cache: /var/folders/np/pd6clpgx1xs_0sdwz71m1gyh0000gn/T/9ede27cf5d2808a997283e6386622428.mpf_cache
2025-02-21 18:29:03,453 : INFO : ConfigProcessor : Loading config from cache: /var/folders/np/pd6clpgx1xs_0sdwz71m1gyh0000gn/T/1a4610a235e3724f4c88b7b6a3726c72.mpf_cache
2025-02-21 18:29:03,453 : INFO : ConfigProcessor : Loading config from cache: /var/folders/np/pd6clpgx1xs_0sdwz71m1gyh0000gn/T/911d1b37f4ad2186d44e0f02a423c49c.mpf_cache
2025-02-21 18:29:03,453 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev6
2025-02-21 18:29:03,453 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2025-02-21-18-29-03-mpf-Mac.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'full_logfile_path': '/Users/andre/Napoleon/logs/2025-02-21-18-29-03-mpf-Mac.log'}
2025-02-21 18:29:03,453 : INFO : Machine : MPF path: /Users/andre/mpf/lib/python3.11/site-packages/mpf
2025-02-21 18:29:03,453 : INFO : Machine : Machine path: /Users/andre/Napoleon
2025-02-21 18:29:03,453 : INFO : Machine : Platform: darwin
2025-02-21 18:29:03,453 : INFO : Machine : Python executable location: /Users/andre/mpf/bin/python3.11
2025-02-21 18:29:03,453 : INFO : Machine : Python version: 3.11.8 (64-bit)
2025-02-21 18:29:03,454 : INFO : Machine : Initializing MPF...
2025-02-21 18:29:03,468 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-02-21 18:29:03,472 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-02-21 18:29:03,472 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev6', 'prev_value': None, 'change': True}
2025-02-21 18:29:03,472 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev6, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-02-21 18:29:03,472 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.11.8', 'prev_value': None, 'change': True}
2025-02-21 18:29:03,480 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'macOS-15.3.1-arm64-arm-64bit', 'prev_value': None, 'change': True}
2025-02-21 18:29:03,480 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Darwin', 'prev_value': None, 'change': True}
2025-02-21 18:29:03,480 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '24.3.0', 'prev_value': None, 'change': True}
2025-02-21 18:29:03,480 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': 'Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:23 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6020', 'prev_value': None, 'change': True}
2025-02-21 18:29:03,480 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'arm64', 'prev_value': None, 'change': True}
2025-02-21 18:29:03,480 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': '/Users/andre/Napoleon/logs/2025-02-21-18-29-03-mpf-Mac.log', 'prev_value': None, 'change': True}
2025-02-21 18:29:03,480 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-02-21 18:29:03,486 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-02-21 18:29:03,487 : INFO : ball_device.bd_plunger : BCH: Initial count: 0
2025-02-21 18:29:03,487 : INFO : ball_device.bd_plunger : State: idle
2025-02-21 18:29:03,487 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished name='Task-55' coro=<BallDevice._initialize_async() done, defined at /Users/andre/mpf/lib/python3.11/site-packages/mpf/devices/ball_device/ball_device.py:196> exception=ConfigFileError('Config validation error: Entry ball_device_counter_ball_switches:ball_device_counter_ball_switches:ball_switches = "s_trough1" is not valid. Device "s_trough1" not found in "switches:" section in your config.')>
Traceback (most recent call last):
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/devices/ball_device/ball_device.py", line 198, in _initialize_async
    await self.ball_count_handler.initialize()
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/devices/ball_device/ball_count_handler.py", line 92, in initialize
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/devices/ball_device/switch_counter.py", line 27, in __init__
    self.config = self.machine.config_validator.validate_config("ball_device_counter_ball_switches", self.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/config_validator.py", line 256, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/config_validator.py", line 699, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/config_validator.py", line 413, in _validate_type_machine
    raise self.validation_error(item, validation_failure_info,
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry ball_device_counter_ball_switches:ball_device_counter_ball_switches:ball_switches = "s_trough1" is not valid. Device "s_trough1" not found in "switches:" section in your config. Error Code: CFE-ConfigValidator-6 (https://missionpinball.org/logs)
2025-02-21 18:29:03,490 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2025-02-21 18:29:03,490 : INFO : Machine : Starting the main run loop with active modes: []
2025-02-21 18:29:03,490 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2025-02-21 18:29:03,490 : INFO : EventManager : Event: ======'init_phase_4'====== Args={}
2025-02-21 18:29:03,490 : INFO : Machine : Shutting down...
2025-02-21 18:29:03,490 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-02-21 18:29:03,490 : ERROR : root : no running event loop
Traceback (most recent call last):
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/commands/game.py", line 229, in __init__
    self.machine.run()
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/machine.py", line 704, in run
    self._run_loop()
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/machine.py", line 804, in _run_loop
    self._crash_shutdown()
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/machine.py", line 749, in _crash_shutdown
    self._do_stop()
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/machine.py", line 739, in _do_stop
    self.events.process_event_queue()
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/events.py", line 842, in process_event_queue
    self._process_queue_event(event=event[0],
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/events.py", line 783, in _process_queue_event
    task = asyncio.create_task(self._run_handlers_sequential(event, callback, kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 381, in create_task
    loop = events.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
